# Generated by Django 2.0.4 on 2024-05-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='账户')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('mail', models.EmailField(max_length=200, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
