# Generated by Django 2.0.4 on 2024-05-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_zwm', models.CharField(max_length=100, verbose_name='区域中文名')),
                ('area_ywm', models.CharField(max_length=100, verbose_name='区域英文名')),
                ('source_website', models.CharField(max_length=200, verbose_name='来源网站')),
                ('source_link', models.CharField(max_length=300, verbose_name='来源链接')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityHousePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_zwm', models.CharField(max_length=100, verbose_name='城市中文名')),
                ('year', models.CharField(max_length=100, verbose_name='年份')),
                ('year_listing_price', models.CharField(max_length=100, verbose_name='年挂牌价格')),
                ('month', models.CharField(max_length=100, verbose_name='月份')),
                ('month_listing_price', models.CharField(max_length=100, verbose_name='月挂牌价格')),
                ('day', models.CharField(max_length=100, verbose_name='日')),
                ('day_listing_price', models.CharField(max_length=100, verbose_name='日挂牌价格')),
                ('week', models.CharField(max_length=100, verbose_name='周')),
                ('week_listing_price', models.CharField(max_length=100, verbose_name='周挂牌价格')),
                ('bsy', models.CharField(max_length=100, verbose_name='比上月')),
                ('bqn', models.CharField(max_length=100, verbose_name='比去年')),
                ('source_website', models.CharField(max_length=200, verbose_name='来源网站')),
                ('source_link', models.CharField(max_length=300, verbose_name='来源链接')),
                ('cj_date', models.CharField(max_length=300, verbose_name='采集日期')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cjgl_app.Area')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_zwm', models.CharField(max_length=100, verbose_name='省份中文名')),
                ('province_ywm', models.CharField(max_length=100, verbose_name='省份英文名')),
                ('city_zwm', models.CharField(max_length=100, verbose_name='城市中文名')),
                ('city_ywm', models.CharField(max_length=100, verbose_name='城市英文名')),
                ('dm', models.CharField(max_length=100, verbose_name='省份城市代码')),
                ('sjdm', models.CharField(max_length=100, null=True, verbose_name='上级代码')),
                ('source_website', models.CharField(max_length=200, verbose_name='来源网站')),
                ('source_link', models.CharField(max_length=300, null=True, verbose_name='来源链接')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_area_zwm', models.CharField(max_length=100, verbose_name='区域地段中文名')),
                ('regional_area_ywm', models.CharField(max_length=100, verbose_name='区域地段英文名')),
                ('source_website', models.CharField(max_length=200, verbose_name='来源网站')),
                ('source_link', models.CharField(max_length=300, verbose_name='来源链接')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cjgl_app.Area')),
            ],
        ),
        migrations.AddField(
            model_name='cityhouseprice',
            name='province_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cjgl_app.ProvinceCity'),
        ),
        migrations.AddField(
            model_name='cityhouseprice',
            name='regional_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cjgl_app.RegionalArea'),
        ),
        migrations.AddField(
            model_name='area',
            name='province_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cjgl_app.ProvinceCity'),
        ),
    ]
