# Generated by Django 2.0.4 on 2024-05-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cjgl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_zwm', models.CharField(max_length=100, verbose_name='来源中文名')),
                ('source_ywm', models.CharField(max_length=100, null=True, verbose_name='来源英文名')),
                ('source_link', models.CharField(max_length=500, null=True, verbose_name='来源链接')),
                ('source_remarks', models.TextField(max_length=500, null=True, verbose_name='来源备注')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_city', models.CharField(max_length=100, verbose_name='来源城市名称')),
                ('source_city_area', models.CharField(max_length=100, null=True, verbose_name='来源城市区域名称')),
                ('source_city_area_regional', models.CharField(max_length=100, null=True, verbose_name='来源城市区域地段名称')),
                ('source_link', models.CharField(max_length=500, verbose_name='来源链接')),
                ('source_remarks', models.TextField(max_length=500, null=True, verbose_name='来源城市备注')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cjgl_app.Source')),
            ],
        ),
    ]
